[package]
name = "asn1-compiler"
version = "0.1.2"
authors = ["Abhijit Gadgil <gabhijit@iitbombay.org>"]
edition = "2018"
description = "ASN.1 Compiler in Rust."
keywords = ["asn1", "per"]
repository = "https://github.com/gabhijit/hampi.git"
license-file = "LICENSE"
readme = "README.md"
include = ["src/**/*.rs", "README.md", "ARChITECTURE.md", "Cargo.toml", "LICENSE", "LICENSE-MIT", "LICENSE-Apache2"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
lazy_static = { version = "1.4.0" }
topological-sort = { version = "0.1" }
proc-macro2 = { version = "1.0" }
quote = { version = "1.0" }
heck = { version = "0.4" }
rustfmt = { version = "0.10" }
#rustfmt-nightly = {git = "https://github.com/rust-lang/rustfmt", rev = "ef57c5bf6751e5a4f548c722d6aeb28f6d86664d" }
#rustfmt-nightly = {git = "https://github.com/rust-lang/rustfmt", branch = "master" }
bitvec = { version = "0.22" }


[[bin]]
name = "hampi-asn1c"
path = "src/bin/hampi-asn1c.rs"
